[root-directory]
hint = "The root directory/root directory of a server is the directory (folder) that is highest up in the server's directory hierarchy. This folder contains the server's startup `.jar` file (usually `server.jar`) (and files such as `server.properties`, the world folder or `eula.txt`, on the BungeeCord server `config.yml`, on Velocity `velocity.toml`)."

[tld]
hint = "The TLD refers to the extension of the domain, so in the domain `mydomain.com` the TLD is `com`"

[subdomain]
hint = "Subdomain is a domain that is a part of another (main) domain. For example, if a domain offered an online store as part of their website `example.com`, it might use the subdomain `shop.example.com`"

[root-domain]
hint = "The root domain refers to the domain itself, e.g. `mydomain.com`. Conversely, e.g. `mc.mydomain.com` is not the root domain but a subdomain."

[backend-server]
hint = "In proxy networks, backend servers mean servers that are not the proxy server itself (Velocity, BungeeCord), but \"classic\" servers the proxy connects, i.e. Paper, Pufferfish, Spigot, etc."